# Generated by Django 4.2.3 on 2023-07-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter proeject name', max_length=200)),
                ('description', models.TextField(help_text='Enter a description', max_length=1000)),
                ('link', models.CharField(max_length=500)),
            ],
        ),
    ]
